# Generated by Django 3.1.2 on 2020-11-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_userorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='orders',
        ),
        migrations.AddField(
            model_name='userorder',
            name='orders',
            field=models.ManyToManyField(to='buy.Cart'),
        ),
    ]
