# Generated by Django 3.1.2 on 2020-11-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('buy', '0005_auto_20201108_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='orders',
        ),
        migrations.AddField(
            model_name='userorder',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
